version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/cicd-app/
    
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777

hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 3000
      runas: ec2-user